create table tb_cidades (id int8 generated by default as identity, name varchar(255), primary key (id));
create table tb_dados (id int8 generated by default as identity, atendimentos int4, date date, valor float8, cidade_id int8, primary key (id));
alter table if exists tb_dados add constraint FKd8mt58g4o3f61c7797h34lmof foreign key (cidade_id) references tb_cidades;
